name: github pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - uses: bahmutov/npm-install@v1

      - run: npm run build

      - run: |
          cd dist
          mkdir vue3-video-player
          mv ./static ./vue3-video-player
          mv ./favicon.ico ./vue3-video-player
          mv ./index.html ./vue3-video-player

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
